services:
  # Banco de dados PostgreSQL apenas
  postgres:
    image: postgres:15
    container_name: gerenciador_clientes_postgres_dev
    environment:
      POSTGRES_DB: gerenciador_clientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - gerenciador_network_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gerenciador_clientes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:

networks:
  gerenciador_network_dev:
    driver: bridge
