services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: gerenciador_clientes_postgres
    environment:
      POSTGRES_DB: gerenciador_clientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gerenciador_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gerenciador_clientes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciador_clientes_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - gerenciador_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  gerenciador_network:
    driver: bridge
